# Generated by Django 2.0.4 on 2018-04-19 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='ProjectWork',
        ),
    ]
