# Generated by Django 2.0.4 on 2018-04-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180419_1248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectWork',
            new_name='Project',
        ),
    ]
