# Generated by Django 2.0.4 on 2018-04-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180419_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='project',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
