# Generated by Django 2.0.4 on 2018-04-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20180419_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
